--DROP DATABASE CUOIKY
CREATE DATABASE CUOIKY
GO

USE CUOIKY

GO

DROP TABLE CUSTOMER
DROP TABLE WAREHOUSE
DROP TABLE BILL
DROP TABLE DETAIL
CREATE TABLE CUSTOMER(
	ID INTEGER NOT NULL,
	name CHAR(30) NOT NULL,
	ADDRESS CHAR(30) CONSTRAINT diachi NOT NULL ,
	PHONE INT CONSTRAINT PHONE NOT NULL,
	EMAIL CHAR(30) NOT NULL,
	PASSWORD CHAR(12) CONSTRAINT PASS NOT NULL,
	PRIMARY KEY(ID)
	)
	GO

CREATE TABLE WAREHOUSE(
	GOODSID INTEGER CONSTRAINT MaSP PRIMARY KEY NOT NULL,
	GOODSNAME CHAR(12) CONSTRAINT TenSP NOT NULL,
	PRICE INTEGER CONSTRAINT GIA CHECK(PRICE>=0) NOT NULL,
	QUANTILY_WH INTEGER CONSTRAINT SLTONKHO CHECK(QUANTILY_WH>=0) NOT NULL
	)
GO




CREATE TABLE BILL(
	IDBILL INTEGER CONSTRAINT MAHD UNIQUE NOT NULL,
	IDCUSTOMER INTEGER CONSTRAINT IDKH FOREIGN KEY(IDCUSTOMER) REFERENCES CUSTOMER(ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	DATE DATETIME CONSTRAINT NGAY NOT NULL,
	SUM INTEGER CONSTRAINT TONG CHECK(SUM>=0)
	PRIMARY KEY (IDBILL)
	)
	Go
CREATE TABLE DETAIL(

	IDBILL INTEGER REFERENCES BILL(IDBILL) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	GOODSID INTEGER REFERENCES WAREHOUSE(GOODSID) ON UPDATE CASCADE NOT NULL ,
	QUANTILY INTEGER CONSTRAINT SL CHECK(QUANTILY>=0) NOT NULL,
	PRICE INTEGER CONSTRAINT GIASP CHECK(PRICE>=0) NOT NULL,
	PRIMARY KEY (IDBILL,GOODSID)
	)
Go

/* số lượng  hàng đặt phải nhỏ hơn số lượng tồn kho
cập nhật hàng trong kho sau khi đặt hàng hoặc cập nhật  */

go

CREATE TRIGGER DatHang ON DETAIL AFTER INSERT AS 

BEGIN
	IF((SELECT QUANTILY FROM INSERTED)>(SELECT QUANTILY_WH FROM WAREHOUSE join inserted on inserted.goodsid=warehouse.goodsid
	Where INSERTED.GOODSID=warehouse.goodsid)  )
	BEGIN
		PRINT'BAN DA NHAP NHIEU HON SL SP TON KHO';
		ROLLBACK;
	END
	ELSE
	BEGIN

		UPDATE WAREHOUSE
		SET QUANTILY_WH = QUANTILY_WH - (
		SELECT QUANTILY
		FROM inserted
		WHERE GOODSID = WAREHOUSE.GOODSID
	)
	FROM WAREHOUSE
	JOIN inserted ON WAREHOUSE.GOODSID = inserted.GOODSID
	END
END
GO
/* cập nhật hàng trong kho sau khi cập nhật đặt hàng */
--DROP TRIGGER CAPNHATDATHANG
GO

CREATE TRIGGER CAPNHATDATHANG on DETAIL after update AS
BEGIN
	IF((SELECT QUANTILY_WH+DELETED.QUANTILY-INSERTED.QUANTILY
		FROM WAREHOUSE INNER JOIN DELETED ON WAREHOUSE.GOODSID=DELETED.GOODSID
		INNER JOIN INSERTED ON WAREHOUSE.GOODSID=INSERTED.GOODSID)
		<0)
	BEGIN
		PRINT'CAP NHAT HANG KHONG THANH CONG'
		ROLLBACK
	END
	ELSE
   BEGIN
   UPDATE WAREHOUSE SET QUANTILY_WH = QUANTILY_WH -
	   (SELECT QUANTILY FROM inserted WHERE GOODSID = WAREHOUSE.GOODSID) +
	   (SELECT QUANTILY FROM deleted WHERE GOODSID = WAREHOUSE.GOODSID)
	   FROM WAREHOUSE 
	   JOIN deleted ON WAREHOUSE.GOODSID = deleted.GOODSID
	END
END
GO
/* cập nhật hàng trong kho khi đơn hàng bị hủy*/
DROP TRIGGER HUYHANG
GO
CREATE TRIGGER HUYHANG ON DETAIL 
AFTER DELETE AS
BEGIN
 UPDATE  WAREHOUSE
 SET QUANTILY_WH+=(SELECT QUANTILY FROM DELETED WHERE GOODSID=WAREHOUSE.GOODSID)
					FROM WAREHOUSE JOIN DELETED ON WAREHOUSE.GOODSID=DELETED.GOODSID
END

GO
-------------------------------------------------------------------------------------------------
INSERT INTO CUSTOMER VALUES(1,'FAF','FASF',213213,'QFAF','123123')
INSERT INTO CUSTOMER VALUES(2,'FAF','FASF',213213,'QFAF','123123')

INSERT INTO WAREHOUSE VALUES(1,'FAF',213213,12)
INSERT INTO WAREHOUSE VALUES(2,'FAF',213213,10)

INSERT INTO BILL VALUES(1,1,'2020',12)
INSERT INTO BILL VALUES(2,1,'2020',10)

INSERT INTO DETAIL VALUES(1,1,6,1)
INSERT INTO DETAIL VALUES(2,2,1,2)



UPDATE CUSTOMER SET ID=1 WHERE ID=5
SELECT *
FROM WAREHOUSE

DELETE DETAIL   WHERE IDBILL=1 AND GOODSID=1
DELETE DETAIL   WHERE IDBILL=2 AND GOODSID=2

UPDATE DETAIL SET QUANTILY=11 WHERE IDBILL=1 AND GOODSID=1
DELETE BILL WHERE IDBILL=2 OR IDBILL=1
SELECT *
FROM DETAIL
